# Generated by Django 3.2.8 on 2021-10-13 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_phone_number_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='number',
            new_name='phone_number',
        ),
    ]
